# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d95fcd0560c8f9faadabfff26b9007e6451919c62be47482905e4e79d4976859d00338189fa30ec5015fc973a79747aca978eceb44934d52def80efa62258a1

test:
  secret_key_base: d07f447fc82d1979c471b17c685e80e1a7f09b21e0e65ff5aa15329f2f4149824a3d2893c8fedc1d71e926c06515104f63f30a7e381c6e35f2310d2b93b8d706

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
